In [1]:
import mediapipe as mp
import cv2
import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import precision_score, accuracy_score, f1_score, recall_score, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

# Drawing helpers
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

### 1. Train Model

#### 1.1. Describe data and split dataset

In [2]:
def rescale_frame(frame, percent=50):
    '''
    Rescale a frame to a certain percentage compare to its original frame
    '''
    width = int(frame.shape[1] * percent/ 100)
    height = int(frame.shape[0] * percent/ 100)
    dim = (width, height)
    return cv2.resize(frame, dim, interpolation = cv2.INTER_AREA)


def describe_dataset(dataset_path: str):
    '''
    Describe dataset
    '''

    data = pd.read_csv(dataset_path)
    print(f"Headers: {list(data.columns.values)}")
    print(f'Number of rows: {data.shape[0]} \nNumber of columns: {data.shape[1]}\n')
    print(f"Labels: \n{data['label'].value_counts()}\n")
    print(f"Missing values: {data.isnull().values.any()}\n")
    
    duplicate = data[data.duplicated()]
    print(f"Duplicate Rows : {len(duplicate.sum(axis=1))}")

    return data


def round_up_metric_results(results) -> list:
    '''Round up metrics results such as precision score, recall score, ...'''
    return list(map(lambda el: round(el, 3), results))

In [ ]:
# df = describe_dataset("./train.csv")
# df = describe_dataset("train_augmented.csv")
df = describe_dataset("train_augmented.csv")
# df.loc[df["label"] == "c", "label"] = 0
# df.loc[df["label"] == "i", "label"] = 1
# df.loc[df["label"] == "H", "label"] = 2
# df.loc[df["label"] == "L", "label"] = 3

label_map = {
    'c': 0,
    'bent_front_knee': 1,
    'arms_dropped': 2,
    'arms_bent': 3,
    'hips_rotated': 4,
    'back_foot_wrong_angle': 5,
    'leaning_forward': 6,
    'narrow_stance': 7,
    'shoulders_not_aligned': 8
}

df["label"] = df["label"].map(label_map)
reverse_map = {v: k for k, v in label_map.items()}



df.head(3)

Headers: ['right_shoulder_x', 'right_shoulder_y', 'right_shoulder_z', 'right_shoulder_v', 'left_heel_x', 'left_heel_y', 'left_heel_z', 'left_heel_v', 'left_index_x', 'left_index_y', 'left_index_z', 'left_index_v', 'nose_x', 'nose_y', 'nose_z', 'nose_v', 'left_foot_index_x', 'left_foot_index_y', 'left_foot_index_z', 'left_foot_index_v', 'right_hip_x', 'right_hip_y', 'right_hip_z', 'right_hip_v', 'right_foot_index_x', 'right_foot_index_y', 'right_foot_index_z', 'right_foot_index_v', 'left_knee_x', 'left_knee_y', 'left_knee_z', 'left_knee_v', 'right_elbow_x', 'right_elbow_y', 'right_elbow_z', 'right_elbow_v', 'right_eye_x', 'right_eye_y', 'right_eye_z', 'right_eye_v', 'left_shoulder_x', 'left_shoulder_y', 'left_shoulder_z', 'left_shoulder_v', 'right_knee_x', 'right_knee_y', 'right_knee_z', 'right_knee_v', 'left_elbow_x', 'left_elbow_y', 'left_elbow_z', 'left_elbow_v', 'right_heel_x', 'right_heel_y', 'right_heel_z', 'right_heel_v', 'left_hip_x', 'left_hip_y', 'left_hip_z', 'left_hip_v', 'left_eye_x', 'left_eye_y', 'left_eye_z', 'left_eye_v', 'right_index_x', 'right_index_y', 'right_index_z', 'right_index_v', 'label']
Number of rows: 3780
Number of columns: 69

Labels:
label
bent_front_knee          420
leaning_forward          420
arms_dropped             420
c                        420
hips_rotated             420
arms_bent                420
shoulders_not_aligned    420
back_foot_wrong_angle    420
narrow_stance            420
Name: count, dtype: int64

Missing values: False

Duplicate Rows : 0

,right_shoulder_x,right_shoulder_y,right_shoulder_z,right_shoulder_v,left_heel_x,left_heel_y,left_heel_z,left_heel_v,left_index_x,left_index_y,...,left_hip_v,left_eye_x,left_eye_y,left_eye_z,left_eye_v,right_index_x,right_index_y,right_index_z,right_index_v,label
0,-0.108334,-1.165313,-0.528089,0.999455,0.734837,1.775910,-0.177590,0.992151,1.211298,-1.178290,...,0.999313,0.287362,-1.657008,-0.620638,0.999962,-0.922404,-1.272223,-1.152376,0.983231,1
1,-0.133418,-1.297389,-1.200911,0.999859,0.503449,1.438582,0.652861,0.963439,1.380505,-1.725864,...,0.999645,0.374783,-1.689237,-0.864244,0.999995,-1.511538,-2.151011,-3.683270,0.984447,6
2,-0.045538,-1.119620,-2.265111,0.999396,-1.918686,0.845442,1.536405,0.994062,-0.241709,-2.017518,...,0.999678,0.243982,-1.456258,-0.154374,0.999891,-0.321848,-0.873728,-3.611444,0.923171,2

In [14]:
# Extract features and class
X = df.drop("label", axis=1)
y = df["label"].astype("int")

In [15]:
sc = StandardScaler()
# X = pd.DataFrame(sc.fit_transform(X))
X = pd.DataFrame(sc.fit_transform(X), columns=X.columns, index=X.index)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)
y_test.head(3)

3150    6
2464    5
305     0
Name: label, dtype: int32

#### 1.2. Train model using Scikit-Learn and train set evaluation

In [17]:
algorithms =[("LR", LogisticRegression()),
         ("SVC", SVC(probability=True)),
         ('KNN',KNeighborsClassifier()),
         ("DTC", DecisionTreeClassifier()),
         ("SGDC", CalibratedClassifierCV(SGDClassifier())),
         ("NB", GaussianNB()),
         ('RF', RandomForestClassifier()),]

models = {}
final_results = []

for name, model in algorithms:
    trained_model = model.fit(X_train, y_train)
    models[name] = trained_model

    # Evaluate model
    model_results = model.predict(X_test)

    p_score = precision_score(y_test, model_results, average=None, labels=[0, 1, 2,3,4,5,6,7,8])
    a_score = accuracy_score(y_test, model_results)
    r_score = recall_score(y_test, model_results, average=None, labels=[0, 1, 2,3,4,5,6,7,8])
    f1_score_result = f1_score(y_test, model_results, average=None, labels=[0, 1, 2,3,4,5,6,7,8])
    cm = confusion_matrix(y_test, model_results, labels=[0, 1, 2,3,4,5,6,7,8])
    final_results.append(( name,  round_up_metric_results(p_score), a_score, round_up_metric_results(r_score), round_up_metric_results(f1_score_result), cm))

In [18]:
# Sort results by F1 score
final_results.sort(key=lambda k: sum(k[4]), reverse=True)

pd.DataFrame(final_results, columns=["Model", "Precision Score", "Accuracy score", "Recall Score", "F1 score", "Confusion Matrix"])

,Model,Precision Score,Accuracy score,Recall Score,F1 score,Confusion Matrix
0,LR,"[0.902, 0.987, 1.0, 0.974, 1.0, 1.0, 1.0, 1.0,...",0.984127,"[1.0, 0.975, 0.976, 0.962, 1.0, 0.988, 0.977, ...","[0.949, 0.981, 0.988, 0.968, 1.0, 0.994, 0.988...","[[83, 0, 0, 0, 0, 0, 0, 0, 0], [2, 78, 0, 0, 0..."
1,SGDC,"[0.94, 1.0, 0.976, 0.974, 0.989, 0.977, 0.977,...",0.978836,"[0.952, 1.0, 0.953, 0.937, 1.0, 0.988, 0.988, ...","[0.946, 1.0, 0.964, 0.955, 0.995, 0.983, 0.983...","[[79, 0, 0, 1, 0, 1, 2, 0, 0], [0, 80, 0, 0, 0..."
2,DTC,"[0.477, 0.921, 0.793, 0.707, 0.967, 0.839, 0.9...",0.822751,"[0.614, 0.875, 0.765, 0.734, 0.956, 0.849, 0.8...","[0.537, 0.897, 0.778, 0.72, 0.961, 0.844, 0.85...","[[51, 4, 5, 7, 1, 6, 6, 3, 0], [9, 70, 1, 0, 0..."
3,RF,"[0.495, 0.921, 0.729, 0.682, 1.0, 0.798, 1.0, ...",0.821429,"[0.602, 0.875, 0.729, 0.759, 0.945, 0.826, 0.8...","[0.543, 0.897, 0.729, 0.719, 0.972, 0.811, 0.9...","[[50, 5, 9, 8, 0, 9, 0, 0, 2], [7, 70, 2, 1, 0..."
4,SVC,"[0.677, 0.97, 0.656, 0.638, 0.976, 0.859, 0.97...",0.814815,"[0.783, 0.812, 0.694, 0.759, 0.912, 0.779, 0.8...","[0.726, 0.884, 0.674, 0.694, 0.943, 0.817, 0.9...","[[65, 0, 3, 5, 0, 3, 2, 2, 3], [4, 65, 4, 2, 0..."
5,KNN,"[0.315, 0.662, 0.718, 0.469, 0.838, 0.443, 0.9...",0.576720,"[0.554, 0.588, 0.6, 0.57, 0.681, 0.547, 0.616,...","[0.402, 0.623, 0.654, 0.514, 0.752, 0.49, 0.75...","[[46, 5, 4, 11, 2, 5, 1, 2, 7], [14, 47, 4, 6,..."
6,NB,"[0.067, 0.155, 0.333, 0.231, 0.435, 0.3, 0.2, ...",0.195767,"[0.012, 0.6, 0.259, 0.038, 0.11, 0.035, 0.605,...","[0.02, 0.246, 0.291, 0.065, 0.175, 0.062, 0.30...","[[1, 36, 6, 2, 0, 2, 31, 2, 3], [2, 48, 6, 1, ..."

#### 1.3. Test set evaluation

In [ ]:
# test_df = describe_dataset("./test.csv")
test_df = describe_dataset("test.csv")
test_df = test_df.sample(frac=1).reset_index(drop=True)

test_df.loc[test_df["label"] == "C", "label"] = 0
test_df.loc[test_df["label"] == "H", "label"] = 1
test_df.loc[test_df["label"] == "L", "label"] = 2

test_x = test_df.drop("label", axis=1)
test_y = test_df["label"].astype("int")

test_x = pd.DataFrame(sc.transform(test_x))

In [ ]:
# Evaluate models on the test sets
testset_final_results = []

for name, model in models.items():
    # Evaluate model
    model_results = model.predict(test_x)

    p_score = precision_score(test_y, model_results, average=None, labels=[0, 1, 2])
    a_score = accuracy_score(test_y, model_results)
    r_score = recall_score(test_y, model_results, average=None, labels=[0, 1, 2])
    f1_score_result = f1_score(test_y, model_results, average=None, labels=[0, 1, 2])
    cm = confusion_matrix(test_y, model_results, labels=[0, 1, 2])
    testset_final_results.append(( name,  round_up_metric_results(p_score), a_score, round_up_metric_results(r_score), round_up_metric_results(f1_score_result), cm ))


testset_final_results.sort(key=lambda k: sum(k[4]), reverse=True)
pd.DataFrame(testset_final_results, columns=["Model", "Precision Score", "Accuracy score", "Recall Score", "F1 score", "Confusion Matrix"])

#### 1.4. Dumped model and input scaler using pickle

According to the evaluations, there are multiple good models at the moment, therefore, the best models are LR and Ridge.

In [ ]:
with open("./model/all_sklearn.pkl", "wb") as f:
    pickle.dump(models, f)

In [ ]:
with open("./model/LR_model.pkl", "wb") as f:
    pickle.dump(models["LR"], f)

In [ ]:
with open("./model/SVC_model.pkl", "wb") as f:
    pickle.dump(models["SVC"], f)

In [ ]:
# Dump input scaler
with open("./model/input_scaler.pkl", "wb") as f:
    pickle.dump(sc, f)